services:
  - type: web
    name: astrella
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GEMINI_API_KEY
        sync: false 